export interface IResponse {
    message: string
    status: boolean
    success: boolean
}


export enum CODIGO_ERRORS {

    PETICION_HTTP_OK = 0,
    PETICION_HTTP_OK_CON_WARNS = 1,
    PETICION_HTTP_INTERNAL = 50000,
    PETICION_HTTP_ERROR_DATA = 8888,
    PETICION_HTTP_REQUIERE_PARAMETRO = 8989,
    PETICION_HTTP_REQUIERE_PARAMETRO_NUEVO = 8990,
    PETICION_HTTP_ERROR_NEGOCIO_VENTA = 8981,
    SIN_CONSECUTIVOS = 8982,
    INVALID_HEADER = 100000,

    INVALID_HEADERS_AUTORIZACION = 40015,
    INVALID_HEADERS_User_Agent = 40016,
    INVALID_HEADERS_UUID = 10001,
    INVALID_HEADERS_FECHA = 10002,
    INVALID_HEADERS_APLICACION = 10003,
    INVALID_HEADERS_IDENTIFICADOR_DISPOSITIVO = 10004,
    INVALID_HEADERS_APLICACION_VERSION = 10005,
    NO_AUTORIZADO = 1250,

    INVALID_ERROR_PARAMETROS = 5000,
    INVALID_DATA_FECHA = 5001,
    INVALID_DATA_ID = 5002,
    INVALID_DATA_VALOR = 5003
}


export enum ResponseErrorTipo {
    TECNICO = 'tecnico',
    BUSSINES = 'negocio'
}


export enum MENSAJES {
    PETICION_HTTP_OK = 'TRANSACCION RECIBIDA',
    PETICION_HTTP_ERROR = 'TRANSACCION NO RECIBIDA'
}


export enum CODIGO_RESPUESTA {
    RECHAZADA = '500',
    PROCESADA = '201',
    RECHAZADA_ERROR = '501',
    RECHAZADA_MOVIMIENTO_NO_EXISTE = '502'
}